---
application:
  name: "gico-api"
  project: "gico-db"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "gico-api-pg-db"
  version: "11"
routers:
- name: "main-gico-api"
  routes:
  - application_name: "gico-api"
    paths:
    - "/*"
